# fly.toml app configuration file generated for avezah-rsshub on 2025-04-13T12:22:37+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'avezah-rsshub'
primary_region = 'hkg'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[http_service]
  internal_port = 1200
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 1200
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[checks]
  [checks.custom_check]
    grace_period = "30s"
    interval = "30s"
    method = "get"
    path = "/healthz"
    port = 1200
    timeout = "10s"
    type = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
